### ISSUE TITLE
Supply voltage usb or 5V pin

### ISSUE THREAD

**Issue by djuscha** [karawin/karadio-addons#2]
If 5V is fed via usb then STM32 is working normally, all commands through encoder or IR are going fast and immediately. If I feed through the pin 5V then it works slowly for a long time thinks for some reason ..
why is that? Use the same voltage supply

**Comment by karawin** [comment]
May be gnd is missing and with usb it is connected by the usb itself?

**Comment by djuscha** [comment]
No, Minus I have connected to GND pin

**Comment by karawin** [comment]
You are right, a problem is discovered but it is a problem only with a control panel and an addon.
If you don't have a control panel, be sure to gnd the A0 input.
I will release a 1.3.3 in one hour max. (edit) done.
Thanks

**Comment by djuscha** [comment]
ok:) Thanks  
A0 is on GND, have no buttons
