### ISSUE TITLE
Error compiling sketch for LCD1602

### ISSUE THREAD

**Issue by h1aji** [karawin/karadio-addons#5]
I am seeing this error:
```

error: 'removeUtf8' was not declared in this scope
   removeUtf8((byte*)line);

```

What type should be set here:
https://github.com/karawin/karadio-addons/blob/5f5a7a8a4664e727c44923243bae4397ddb810e6/karadiolcd16x2/karadiolcd16x2.ino#L103

?

Is it byte?

**Comment by konzolec** [comment]
I'm also haing trouble with compiling  

karadioU8STM32:341:76: error: invalid conversion from 'uint8_t ()(u8g_t, uint8_t, uint8_t, void*) {aka unsigned char ()(_u8g_t, unsigned char, unsigned char, void*)}' to 'uint8_t {aka unsigned char}' [-fpermissive]
U8GLIB_SSD1306_128X64 u8g((u8g_com_fnptr)u8g_com_hw_i2c_fn,U8G_I2C_OPT_NONE);

**Comment by karawin** [comment]
Just comment it 
//removeUtf8((byte*)line); 
or erase the line
